# Basic LAMP stack

version: "2.1"

services:
  # Web
  web:
    hostname: web
    image: ${WEB_IMAGE}
    volumes:
      # Project root volume
      - project_root:/var/www:ro
    ports:
      - "8083:80"
      - "4433:443"
    labels:
      - io.docksal.virtual-host=${VIRTUAL_HOST},*.${VIRTUAL_HOST}
      - io.docksal.project-root=${PROJECT_ROOT}
    environment:
      - APACHE_DOCUMENTROOT=/var/www/${DOCROOT:-docroot}
    depends_on:
      - cli
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}

  # DB
  db:
    hostname: db
    image: ${DB_IMAGE}
    ports:
      - "${MYSQL_PORT_MAPPING:-3306}"
    volumes:
      # Project root volume
      # - ${project_root:/var/www:ro
      - ${PROJECT_ROOT}/db:/docker-entrypoint-initdb.d:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_USER=${MYSQL_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-user}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-default}
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}

  # CLI
  # Used for all console commands and tools.
  cli:
    hostname: cli
    image: ${CLI_IMAGE}
    volumes:
      # Project root volume
      - project_root:/var/www:rw
      # Shared ssh-agent socket
      - docksal_ssh_agent:/.ssh-agent:ro
    environment:
      - XDEBUG_ENABLED=0
      - XDEBUG_CONFIG=idekey=PHPSTORM remote_host=192.168.10.1
      - PHP_IDE_CONFIG=serverName=${VIRTUAL_HOST}
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}


  # elasticsearch:
  #   hostname: elasticsearch
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
  #   ports:
  #     - "9200:9200"
  #   environment:
  #     HTTP_CORS_ALLOW-ORIGIN: '*'
  #     HTTP_CORS_ENABLED: 1
  #     XPACK_SECURITY_ENABLED: 'false'
  #     XPACK_ML_ENABLED: 'false'
  #     XPACK_MONITORING_ENABLED: 'false'
  #     XPACK_WATCHER_ENABLED: 'false'
  #   dns:
  #     - ${DOCKSAL_DNS1}
  #     - ${DOCKSAL_DNS2}

  # kibana:
  #   hostname: kibana
  #   image: docker.elastic.co/kibana/kibana:6.4.1
  #   ports:
  #     - "5601:5601"
  #   environment:
  #     ELASTICSEARCH_URL: http://192.168.64.100:9200
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
